import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import Scene from './Scene.jsx';
import Player from './Player.jsx';
import {position} from '../server/clock.mjs';
import './style.css';
const format=t=>`${Math.floor(Math.max(0,t)/60)}:${String(Math.floor(Math.max(0,t)%60)).padStart(2,'0')}`;
async function api(path,data){const r=await fetch(path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(data)});const b=await r.json();if(!r.ok)throw Error(b.error);return b;}
function App(){
 const [roomId,setRoomId]=useState(new URL(location.href).searchParams.get('room')||''),[room,setRoom]=useState(null),[self,setSelf]=useState(''),[host,setHost]=useState(false),[name,setName]=useState(localStorage.getItem('ah-name')||''),[color,setColor]=useState(localStorage.getItem('ah-color')||'#d9a566'),[joined,setJoined]=useState(false),[online,setOnline]=useState(false),[notice,setNotice]=useState(''),[enabled,setEnabled]=useState(false),[status,setStatus]=useState('Som desativado'),[query,setQuery]=useState(''),[results,setResults]=useState([]),[link,setLink]=useState(''),[tab,setTab]=useState('queue'),[admin,setAdmin]=useState(false),[adminKey,setAdminKey]=useState(''),[now,setNow]=useState(Date.now()),[roomName,setRoomName]=useState('A nossa listening room');
 const socket=useRef(),clock=useRef({offset:Date.now()-performance.now(),rtt:Infinity}),roomRef=useRef();roomRef.current=room;
 const serverNow=()=>performance.now()+clock.current.offset;
 const send=m=>{if(socket.current?.readyState===1)socket.current.send(JSON.stringify(m));else setNotice('A ligação à sala está a recuperar.');};
 useEffect(()=>{const t=setInterval(()=>setNow(serverNow()),250);return()=>clearInterval(t)},[]);
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),8000);return()=>clearTimeout(t)},[notice]);
 useEffect(()=>{
  if(!joined||!roomId)return;let stopped=false,retry,timer;const connect=()=>{
   const ws=new WebSocket(`${location.protocol==='https:'?'wss:':'ws:'}//${location.host}/ws`);socket.current=ws;
   ws.onopen=()=>{setOnline(true);clock.current.rtt=Infinity;ws.send(JSON.stringify({type:'join',room:roomId,name,color,token:sessionStorage.getItem('ah-host:'+roomId)||''}));const ping=()=>ws.readyState===1&&ws.send(JSON.stringify({type:'ping',t:performance.now()}));ping();timer=setInterval(ping,3000);};
   ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.type==='welcome'){setSelf(m.id);setHost(m.host);}if(m.type==='state'){setRoom(prev=>!prev||m.room.revision>=prev.revision?m.room:prev);}if(m.type==='move')setRoom(prev=>prev?{...prev,members:prev.members.map(p=>p.id===m.id?{...p,x:m.x,z:m.z}:p)}:prev);if(m.type==='pong'){const rtt=performance.now()-m.t;if(rtt<=clock.current.rtt+10){clock.current={rtt,offset:m.serverTime-(m.t+performance.now())/2};}}if(m.type==='results'){setResults(m.tracks);setTab('search');}if(m.type==='error'||m.type==='notice')setNotice(m.message);};
   ws.onclose=()=>{setOnline(false);clearInterval(timer);if(!stopped)retry=setTimeout(connect,1800);};ws.onerror=()=>setOnline(false);
  };connect();return()=>{stopped=true;clearTimeout(retry);clearInterval(timer);socket.current?.close();};
 },[joined,roomId]);
 async function enter(create){try{if(!name.trim())throw Error('Escolhe o teu nome.');let id=roomId;if(create){const r=await api('/api/rooms',{name:roomName});id=r.id;sessionStorage.setItem('ah-host:'+id,r.hostToken);setRoomId(id);history.replaceState(null,'','?room='+id);}if(!/^[a-f\d]{12}$/.test(id))throw Error('Cola o código da sala ou abre o convite.');localStorage.setItem('ah-name',name);localStorage.setItem('ah-color',color);setJoined(true);}catch(e){setNotice(e.message);}}
 const current=room?.queue.find(t=>t.id===room.playback.trackId),time=room?position(room.playback,now):0;
 const control=(action,value)=>send({type:'control',action,value});
 const importLink=()=>{if(!link.trim())return;send(host?{type:link.includes('open.spotify.com/')?'import':'add',url:link}:{type:'request',url:link});};
 return <main>
  <Scene members={room?.members||[]} self={self} onMove={p=>send({type:'move',...p})} track={current} playback={room?.playback} position={time}/>
  <header><a className="brand" href="/">afterhours<span> / listening room</span></a><div className="header-right">{joined&&<><span className={'connection '+(online?'connected':'')}>{online?'Ligado':'A reconectar…'}</span><button onClick={()=>navigator.clipboard.writeText(location.origin+'/?room='+roomId).then(()=>setNotice('Convite copiado.')).catch(()=>setNotice('Código da sala: '+roomId))}>Convidar amigos ↗</button></>}<button onClick={()=>setAdmin(true)} aria-label="Definições de administrador">⚙</button></div></header>
  {!joined?<section className="welcome"><div className="eyebrow">O TEU CANTO DEPOIS DAS HORAS</div><h1>Boa música.<br/>A tua companhia.</h1><p>Entra, escolhe um lugar e partilha o próximo som.</p><label>O teu nome<input maxLength={24} value={name} onChange={e=>setName(e.target.value)} placeholder="Como te chamam?"/></label><div className="colors" aria-label="Cor do avatar">{['#d9a566','#a9bcc5','#bd8e98','#93ae8c','#bba5d6'].map(c=><button key={c} style={{background:c}} aria-label={'Cor '+c} aria-pressed={color===c} onClick={()=>setColor(c)}>{c===color?'✓':''}</button>)}</div>{!roomId&&<label>Nome da sala<input value={roomName} onChange={e=>setRoomName(e.target.value)} maxLength={40}/></label>}<button className="primary" onClick={()=>enter(!roomId)}>{roomId?'Entrar na sala':'Criar sala'} →</button><details><summary>Tenho um código de sala</summary><input aria-label="Código de sala" placeholder="Código ou link do convite" value={roomId} onChange={e=>{let v=e.target.value;try{v=new URL(v).searchParams.get('room')||v;}catch{}setRoomId(v)}}/><button onClick={()=>enter(false)}>Entrar</button></details></section>:<>
   <div className="room-heading"><div className="eyebrow">SESSÃO PARTILHADA</div><h1>{room?.name||'A entrar…'}</h1><p>{host?'És o anfitrião. Escolhe o próximo som.':'A música é controlada pelo anfitrião.'}</p><div className="member-chips">{room?.members.map(m=><span key={m.id}><i style={{background:m.color}}/>{m.name}{m.host?' ♛':''}</span>)}</div></div>
   <aside className="music-panel"><div className="panel-tabs"><button className={tab==='queue'?'selected':''} onClick={()=>setTab('queue')}>Fila <small>{room?.queue.length||0}</small></button><button className={tab==='search'?'selected':''} onClick={()=>setTab('search')}>Descobrir</button><button className={tab==='requests'?'selected':''} onClick={()=>setTab('requests')}>Pedidos <small>{room?.requests.length||0}</small></button></div>
    <div className="panel-body">{tab==='queue'&&<>{!room?.queue.length&&<div className="empty"><span>♫</span><h2>O primeiro som é teu.</h2><p>Pesquisa no Audius ou adiciona uma playlist para começar.</p></div>}{room?.queue.map((t,i)=><article className={'track '+(t.id===current?.id?'current':'')} key={t.id}><div className="track-number">{t.id===current?.id?'♫':String(i+1).padStart(2,'0')}</div><div className="track-copy"><strong>{t.title}</strong><span>{t.artist}</span><small>{({ready:t.provider,matching:'A procurar…',review:'Confirmar versão',unavailable:'Não disponível'})[t.status]}</small>{t.spotifyUrl&&<a href={t.spotifyUrl} target="_blank" rel="noreferrer">Origem: Spotify ↗</a>}{host&&t.status==='review'&&t.candidates?.map((c,index)=><button className="candidate" key={index} onClick={()=>send({type:'approve',id:t.id,index})}>Usar: {c.title} · {c.artist} ({c.provider})</button>)}</div>{host&&t.status==='ready'&&<button aria-label={'Reproduzir '+t.title} onClick={()=>control('select',t.id)}>▶</button>}</article>)}</>}
    {tab==='search'&&<><form onSubmit={e=>{e.preventDefault();send({type:'search',query});}}><label>Pesquisar no Audius<div className="input-row"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Artista ou música" required/><button type="submit">⌕</button></div></label></form>{results.map(t=><article className="track" key={t.sourceId}><div className="track-copy"><strong>{t.title}</strong><span>{t.artist}</span><a href={t.url} target="_blank" rel="noreferrer">Audius ↗</a></div>{host&&<button aria-label={'Adicionar '+t.title} onClick={()=>send({type:'add',audiusId:t.sourceId,query})}>＋</button>}</article>)}</>}
    {tab==='requests'&&<>{!room?.requests.length&&<p className="empty">Ainda não há pedidos. Partilha uma música com a sala.</p>}{room?.requests.map(r=><article className="request" key={r.id}><strong>{r.by}</strong><a href={r.url} target="_blank" rel="noreferrer">{r.url}</a>{host&&<div><button onClick={()=>{setLink(r.url);setNotice('Pedido copiado para o campo. Carrega em Adicionar.');}}>Preparar</button><button onClick={()=>send({type:'dismiss',id:r.id})}>Remover</button></div>}</article>)}</>}
    </div><div className="add-box"><label>{host?'Adicionar música ou playlist':'Pedir música ou playlist'}<input value={link} onChange={e=>setLink(e.target.value)} placeholder="Cola um link Spotify, SoundCloud ou YouTube"/></label><button onClick={importLink}>{host?'Adicionar à sala':'Enviar pedido'} ＋</button></div>
   </aside>
   <section className="now-playing" aria-label="Projetor e reprodução"><div className="now-top">{current?.cover?<img src={current.cover} alt={'Capa: '+current.title}/>:<div className="record">♫</div>}<div><small>NO PROJETOR</small><h2>{current?.title||'À espera do primeiro som'}</h2><p>{current?.artist||'Escolhe uma faixa na fila'}</p></div></div><Player track={current} playback={room?.playback} enabled={enabled&&online} serverNow={serverNow} onEnded={id=>host&&send({type:'control',action:'ended',trackId:id})} onStatus={setStatus}/><div className="timeline"><span>{format(time)}</span><input aria-label="Posição da música" type="range" min="0" max={current?.duration||Math.max(time,1)} value={Math.min(time,current?.duration||time)} step=".1" disabled={!host||!current?.duration} onChange={e=>control('seek',Number(e.target.value))}/><span>{current?.duration?format(current.duration):'—'}</span></div><div className="transport"><button className="enable" onClick={()=>{window.dispatchEvent(new CustomEvent('afterhours-audio',{detail:!enabled}));setEnabled(!enabled);setStatus(!enabled?'A ativar som…':'Som desativado')}}>{enabled?'♬ Som ativo':'Ativar som'}</button>{host&&<><button disabled={!current||!online} className="play" aria-label={room?.playback.playing?'Pausar':'Reproduzir'} onClick={()=>control(room?.playback.playing?'pause':'play')}>{room?.playback.playing?'Ⅱ':'▶'}</button><button disabled={!online} onClick={()=>control('next')} aria-label="Próxima música">▶|</button></>}<small>{enabled?status:'Clica para ouvir neste browser'}</small></div></section>
   <div className="move-guide">WASD / setas · Clica no chão para andar · Arrasta para rodar</div>
  </>}
  {notice&&<div className="notice" role="status">{notice}<button onClick={()=>setNotice('')} aria-label="Fechar aviso">×</button></div>}
  {admin&&<div className="modal-backdrop"><section className="admin-modal" role="dialog" aria-modal="true" aria-labelledby="admin-title"><button className="close" onClick={()=>setAdmin(false)}>×</button><h2 id="admin-title">Spotify do anfitrião</h2><p>Apenas para importar metadados de playlists tuas ou em que és colaborador. A autorização fica guardada no servidor.</p><label>Chave de administrador<input type="password" autoComplete="current-password" value={adminKey} onChange={e=>setAdminKey(e.target.value)}/></label><button className="primary" onClick={async()=>{try{await api('/api/admin/login',{key:adminKey});setAdminKey('');const r=await api('/api/spotify/connect',{room:roomId});location.assign(r.url);}catch(e){setNotice(e.message)}}}>Ligar Spotify</button></section></div>}
 </main>;
}
createRoot(document.getElementById('root')).render(<App/>);
